# Dependabot configuration file for GitHub

version: 2
updates:
  # CI workflow action updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"

  # Gradle package updates
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    ignore:
      - dependency-name: 'org.spigotmc:spigot-api'
      - dependency-name: 'org.papermc:paper-api'
      - dependency-name: 'net.md-5:bungeecord-api'
      - dependency-name: 'net.dv8tion:JDA'